### ISSUE TITLE
Scheduler quietly dies forever if mysql backend is not availabe

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#109]
Originally reported by: **Eric Cerfonteyn (Bitbucket: [ericcerfonteyn](http://bitbucket.org/ericcerfonteyn), GitHub: [ericcerfonteyn](http://github.com/ericcerfonteyn))**
---

If connection to a mysql backend blips for any reason during the scheduler wakeup, the following exception is logged, and the scheduler thread dies forever.

```
Exception in thread APScheduler:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "../lib/python2.7/site-packages/apscheduler/schedulers/blocking.py", line 27, in _main_loop
    wait_seconds = self._process_jobs()
  File "../lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 801, in _process_jobs
    for job in jobstore.get_due_jobs(now):
  File "../lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 64, in get_due_jobs
    return self._get_jobs(self.jobs_t.c.next_run_time <= timestamp)
  File "../lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 124, in _get_jobs
    for row in self.engine.execute(selectable):
  File "../lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1751, in execute
    return connection.execute(statement, *multiparams, **params)
  File "../lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 729, in execute
    return meth(self, multiparams, params)
  File "../lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 322, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "../lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 826, in _execute_clauseelement
    compiled_sql, distilled_params
  File "../lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 958, in _execute_context
    context)
  File "../lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1159, in _handle_dbapi_exception
    exc_info
  File "../lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 199, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "../lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 951, in _execute_context
    context)
  File "../lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 436, in do_execute
    cursor.execute(statement, parameters)
  File "../lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "../lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (OperationalError) (2013, 'Lost connection to MySQL server during query') 'SELECT apscheduler_jobs.id, apscheduler_jobs.job_state \nFROM apscheduler_jobs \nWHERE apscheduler_jobs.next_run_time <= %s ORDER BY apscheduler_jobs.next_run_time' (1452250680.008571,)


```
---
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/109

**Comment by Nilom** [comment]
> The way I'm currently handling it is to periodically check that the scheduler's thread is running, then send a signal to restart the entire application if it's not, which I can luckily do in this case.

can any one give some more detail, how to do this?
