### ISSUE TITLE
v3.1.0: AttributeError: 'IntervalTrigger' object has no attribute '__dict__'

### ISSUE THREAD

**Issue by antivirtel** [agronholm/apscheduler#121]
After [upgrading to Flexget v1.2.500, which will upgrade APscheduler to v3.1.0](https://github.com/Flexget/Flexget/issues/1005), I got this crash. The traceback is pasted. Do I need to worry about this?

```
2016-04-03 13:28 ERROR    apscheduler.jobstores                 Unable to restore job "527a1814bb7c58106711f1f3fa208c5efb3b5af2" -- removing it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 119, in _reconstitute_job
    job_state = pickle.loads(job_state)
AttributeError: 'IntervalTrigger' object has no attribute '__dict__'
2016-04-03 13:28 ERROR    apscheduler.jobstores                 Unable to restore job "3805830e723214ea9ef8468e43184f0a70ca5b57" -- removing it
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/jobstores/sqlalchemy.py", line 119, in _reconstitute_job
    job_state = pickle.loads(job_state)
AttributeError: 'IntervalTrigger' object has no attribute '__dict__'
```

These issues might be related: #16 , #70, #97, #107

**Comment by agronholm** [comment]
Do you have code that reproduces this problem? Could it be that flexget 
just upgraded to APScheduler v3 from v2?

03.04.2016, 15:23, B. Roland kirjoitti:

**Comment by agronholm** [comment]
Flexget does not seem to have anything to do with APScheduler so why is this relevant? Why did you say Flexget v1.2.500 will upgrade to APScheduler v3.1.0?

**Comment by antivirtel** [comment]
Thank you for the quick reply!
I don't think so, the requirements.txt didn't change in v1.2.500, just there was a new apscheduler in pip, so it was upgraded too. (that's why I wrote, that it is related! It showed up, after upgrading apscheduler to this new version). I assume, that the previous release was just only a point release, so there was no major upgrade (from v2 to v3). However, @cvium fix me, if I'm wrong!

**Comment by agronholm** [comment]
If your app broke after upgrading to a newer APScheduler point release, I'd like to know how that happened. Can you post code to reproduce the problem?

**Comment by antivirtel** [comment]
I just upgraded from 1.2.499, like this, try:
```bash
pip install flexget==1.2.499
# Add some config with a schedule (flexget.com/wiki)
flexget check && flexget daemon start -d
flexget daemon stop && pip install -U flexget
```

Ps., I can send you my full config in a private channel!

**Comment by agronholm** [comment]
I suggest you visit #apscheduler on Freenode IRC.
