### ISSUE TITLE
3.1.0 apscheduler crash

### ISSUE THREAD

**Issue by Nihim** [agronholm/apscheduler#122]
When trying to run flexget I get the following crash, downgrading apscheduler to 3.0.5 works fine.

```
flexget daemon start
Traceback (most recent call last):
  File "./flexget/bin/flexget", line 11, in <module>
    sys.exit(main())
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/__init__.py", line 37, in main
    manager.start()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/manager.py", line 303, in start
    self.handle_cli()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/manager.py", line 327, in handle_cli
    self.daemon_command(command_options)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/manager.py", line 393, in daemon_command
    fire_event('manager.daemon.started', self)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/event.py", line 103, in fire_event
    result = event(*args, **kwargs)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/event.py", line 22, in __call__
    return self.func(*args, **kwargs)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/plugins/daemon/scheduler.py", line 143, in setup_scheduler
    setup_jobs(manager)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/flexget/plugins/daemon/scheduler.py", line 165, in setup_jobs
    existing_job_ids = [job.id for job in scheduler.get_jobs()]
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 511, in get_jobs
    jobs.extend(store.get_all_jobs())
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 81, in get_all_jobs
    jobs = self._get_jobs()
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 133, in _get_jobs
    for row in self.engine.execute(selectable):
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1991, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 200, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/nihim/flexget/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: apscheduler_jobs [SQL: u'SELECT apscheduler_jobs.id, apscheduler_jobs.job_state \nFROM apscheduler_jobs ORDER BY apscheduler_jobs.next_run_time']
```

**Comment by agronholm** [comment]
This is related to #121. APScheduler 3.1.0 now (correctly) initializes the job store not in the constructor but in the job store's start() method. This, however, is problematic when FlexGet calls get_jobs() before starting the scheduler. At that point, the table hasn't been created yet.

**Comment by antivirtel** [comment]
Related to #121.

**Comment by agronholm** [comment]
Fixed in https://github.com/Flexget/Flexget/pull/1234.
