### ISSUE TITLE
apscheduler & pyinstaller

### ISSUE THREAD

**Issue by mraky** [agronholm/apscheduler#158]
have issue with conbination:

- latest apscheduler
- python 3.5
- latest pyinstaller..

code fragment:
```
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.triggers.interval import IntervalTriggerscheduler= BackgroundScheduler()
scheduler.start()
scheduler.add_job(....
```
//code works fine.  in case i try to pack it with pyinstaller -F <script_name> i am getting following error....  i assume, there is some dynamic import, which i am missing...

```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "c:\users\tra20\app\python_anaconda\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\setuptools-20.3-py3.5.egg\pkg_resources\__init__.py", line 75, in <module>
  File "site-packages\setuptools-20.3-py3.5.egg\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
Failed to execute script pyi_rth_pkgres
```

anyone have any idea, how to make it working ? what import i should add ?

**Comment by agronholm** [comment]
Is this a bug report or a feature request on APScheduler? If neither, this doesn't belong here.

**Comment by mraky** [comment]
it is not feature request... i belive it is more relevant to open issue with apsscheduler, as i think here is higher chance to get answer, then with pyinstaller. anyway. if you really think it is offtopic,  please close it .

**Comment by agronholm** [comment]
Closing as not an APScheduler issue.

**Comment by cfoisy-osisoft** [comment]
I ran into a similar problem with APScheduler 3.3.1 and pyinstaller:
```
pi@raspberrypi:~/Soft/dist $ ./acpbuffer
Traceback (most recent call last):
  File "acpbuffer.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/home/pi/miniconda3/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/apscheduler/__init__.py", line 2, in <module>
  File "site-packages/setuptools-18.1-py3.4.egg/pkg_resources/__init__.py", line 551, in get_distribution
  File "site-packages/setuptools-18.1-py3.4.egg/pkg_resources/__init__.py", line 431, in get_provider
  File "site-packages/setuptools-18.1-py3.4.egg/pkg_resources/__init__.py", line 952, in require
  File "site-packages/setuptools-18.1-py3.4.egg/pkg_resources/__init__.py", line 839, in resolve
pkg_resources.DistributionNotFound: The 'APScheduler' distribution was not found and is required by the application
Failed to execute script acpbuffer
``` 
The following change to `__init__.py` fixes this problem:
```# These will be removed in APScheduler 4.0.
release = "3.3.1cf" # __import__('pkg_resources').get_distribution('APScheduler').version.split('-')[0]
version_info = "3.3.1cf" # tuple(int(x) if x.isdigit() else x for x in release.split('.'))
version = __version__ = '.'.join(str(x) for x in version_info[:3])
```
