### ISSUE TITLE
Don't work~~~Cent0s

### ISSUE THREAD

**Issue by smarttang** [agronholm/apscheduler#159]
`Traceback (most recent call last):
  File "a.py", line 1, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "/usr/lib/python2.6/site-packages/APScheduler-3.2.0-py2.6.egg/apscheduler/schedulers/blocking.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler, STATE_STOPPED
  File "/usr/lib/python2.6/site-packages/APScheduler-3.2.0-py2.6.egg/apscheduler/schedulers/base.py", line 177
    with self._jobstores_lock, self._executors_lock:
                             ^
SyntaxError: invalid syntax
`

**Comment by agronholm** [comment]
APScheduler requires at least Python 2.7. Seems like you're trying to run it on 2.5 or earlier if the `with` statement causes a SyntaxError.

**Comment by agronholm** [comment]
Correction: combining two "with" expressions on the same line requires Python 2.7. That's the problem.

**Comment by smarttang** [comment]
OK!!!
