### ISSUE TITLE
Bug about six in Python 2.7 AttributeError: 'function' object has no attribute 'iteritems'

### ISSUE THREAD

**Issue by 631068264** [agronholm/apscheduler#184]
```
from datetime import datetime

from apscheduler.schedulers.background import BackgroundScheduler


def job():
    print(datetime.now().strftime("%Y-%m-%d %H:%M:%S"))


scheduler = BackgroundScheduler(job)
scheduler.add_job(job, 'interval', seconds=3)
scheduler.start()
print('Press Ctrl+C to exit')
```

```
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/wechat-robot/test.py", line 20, in <module>
    scheduler = BackgroundScheduler(job)
  File "/Users/wyx/bitcoin_workspace/wechat-robot/.env/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 82, in __init__
    self.configure(gconfig, **options)
  File "/Users/wyx/bitcoin_workspace/wechat-robot/.env/lib/python2.7/site-packages/apscheduler/schedulers/base.py", line 104, in configure
    gconfig = dict((key[prefixlen:], value) for key, value in six.iteritems(gconfig)
  File "/Users/wyx/bitcoin_workspace/wechat-robot/.env/lib/python2.7/site-packages/six.py", line 599, in iteritems
    return d.iteritems(**kw)
AttributeError: 'function' object has no attribute 'iteritems'
```

**Comment by agronholm** [comment]
It's not a bug – you're trying to pass a function to `BackgroundScheduler` where a dictionary is expected.
