### ISSUE TITLE
What is look up object?

### ISSUE THREAD

**Issue by 631068264** [agronholm/apscheduler#198]
APScheduler (3.3.1)

I use this code to do my job When I use Memory as job store it can work well but I have too many job and my Memory in server is limit so I change SQLAlchemyJobStore as job strore but I got the Lookup error. How to solve it.

Code:
```
def script(indicator, strategy_name, real_time=False):
    # Solve No handlers could be found for logger “apscheduler.scheduler
    import logging
    logging.basicConfig(level=logging.ERROR,
                        format='%(name)-12s %(asctime)s %(levelname)-8s %(message)s',
                        datefmt='%a, %d %b %Y %H:%M:%S')
    try:
        job_defaults = {
            'coalesce': False,
            'max_instances': 1,
            "misfire_grace_time": config.real_time_script_interval + 5,
        }
        executors = {
            'default': ThreadPoolExecutor(60),
        }
        jobstores = {
            "default": SQLAlchemyJobStore(url='sqlite:///jobs.sqlite')
        }

        scheduler = BlockingScheduler(daemonic=True, jobstores=jobstores, job_defaults=job_defaults,
                                      executors=executors)
        module = __import__("%s.%s" % (indicator, strategy_name), fromlist=[strategy_name])
        if real_time:
            for st in module.strategy:
                scheduler.add_job(st.run, "interval", seconds=config.real_time_script_interval)
        else:
            for st in module.strategy:
                # 计算最近的下一个准点时间
                start_time = _recent_time(st.run_period)
                scheduler.add_job(st.run, "interval", **start_time)
        scheduler.start()
    except Exception as e:
        logger.get("run-log").error(error_msg())
```

Error:
```
apscheduler.jobstores.default Thu, 06 Apr 2017 10:50:32 ERROR    Unable to restore job "d100a4b24e2d49c3ad51305fd846e5f5" -- removing it
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 122, in _reconstitute_job
    job.__setstate__(job_state)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/job.py", line 260, in __setstate__
    self.func = ref_to_obj(self.func_ref)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/util.py", line 277, in ref_to_obj
    raise LookupError('Error resolving reference %s: error looking up object' % ref)
LookupError: Error resolving reference base.strategy:Strategy.run: error looking up object
apscheduler.jobstores.default Thu, 06 Apr 2017 10:50:32 ERROR    Unable to restore job "2602167cd3c745c2b0764a2b63da1a3a" -- removing it
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 122, in _reconstitute_job
    job.__setstate__(job_state)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/job.py", line 260, in __setstate__
    self.func = ref_to_obj(self.func_ref)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/util.py", line 277, in ref_to_obj
    raise LookupError('Error resolving reference %s: error looking up object' % ref)
LookupError: Error resolving reference base.strategy:Strategy.run: error looking up object
apscheduler.jobstores.default Thu, 06 Apr 2017 10:50:32 ERROR    Unable to restore job "3eb917670e7642b8848a165268df8913" -- removing it
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 135, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/jobstores/sqlalchemy.py", line 122, in _reconstitute_job
    job.__setstate__(job_state)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/job.py", line 260, in __setstate__
    self.func = ref_to_obj(self.func_ref)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/apscheduler/util.py", line 277, in ref_to_obj
    raise LookupError('Error resolving reference %s: error looking up object' % ref)
LookupError: Error resolving reference base.strategy:Strategy.run: error looking up object


```

**Comment by agronholm** [comment]
Answering this on [StackOverflow](http://stackoverflow.com/questions/43245034/apscheduler-look-up-object-error).
