### ISSUE TITLE
scheduler thread die because of database connection

### ISSUE THREAD

**Issue by qingyunha** [agronholm/apscheduler#213]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 551, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 504, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/APScheduler-3.0.4-py2.7.egg/apscheduler/schedulers/blocking.py", line 27, in _main_loop
    wait_seconds = self._process_jobs()
  File "/opt/proj/src/proj/scheduler.py", line 22, in _process_jobs
    wait_seconds = super(MScheduler, self)._process_jobs()
  File "/usr/local/lib/python2.7/dist-packages/APScheduler-3.0.4-py2.7.egg/apscheduler/schedulers/base.py", line 801, in _process_jobs
    for job in jobstore.get_due_jobs(now):
  File "/usr/local/lib/python2.7/dist-packages/APScheduler-3.0.4-py2.7.egg/apscheduler/jobstores/mongodb.py", line 65, in get_due_jobs
    return self._get_jobs({'next_run_time': {'$lte': timestamp}})
  File "/usr/local/lib/python2.7/dist-packages/APScheduler-3.0.4-py2.7.egg/apscheduler/jobstores/mongodb.py", line 118, in _get_jobs
    for document in self.collection.find(conditions, ['_id', 'job_state'], sort=[('next_run_time', ASCENDING)]):
  File "/usr/local/lib/python2.7/dist-packages/pymongo-3.2-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 1097, in next
    if len(self.__data) or self._refresh():
  File "/usr/local/lib/python2.7/dist-packages/pymongo-3.2-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 1019, in _refresh
    self.__read_concern))
  File "/usr/local/lib/python2.7/dist-packages/pymongo-3.2-py2.7-linux-x86_64.egg/pymongo/cursor.py", line 903, in __send_message
    codec_options=self.__codec_options)
  File "/usr/local/lib/python2.7/dist-packages/pymongo-3.2-py2.7-linux-x86_64.egg/pymongo/helpers.py", line 120, in _unpack_response
    raise NotMasterError(error_object["$err"], error_object)
NotMasterError: not master and slaveOk=false
```
is there a way to monitor the thread and restart it?

**Comment by agronholm** [comment]
This has already been fixed in a later APScheduler version. Please upgrade.
