### ISSUE TITLE
ValueError: The following arguments have not been supplied: name

### ISSUE THREAD

**Issue by eromoe** [agronholm/apscheduler#251]
APScheduler (3.4.0)

got error:

```
Traceback (most recent call last):
  File "D:\Python27\lib\site-packages\flask\app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python27\lib\site-packages\flask\app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python27\lib\site-packages\flask\app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "Z:/bidspy-yychen/scheduler\scheduler\views.py", line 100, in job_create
    job = current_app.apscheduler.add_job(order['id'], func, trigger=order['trigger'],**params)
  File "D:\Python27\lib\site-packages\flask_apscheduler\scheduler.py", line 146, in add_job
    return self._scheduler.add_job(**job_def)
  File "D:\Python27\lib\site-packages\apscheduler\schedulers\base.py", line 425, in add_job
    job = Job(self, **job_kwargs)
  File "D:\Python27\lib\site-packages\apscheduler\job.py", line 44, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "D:\Python27\lib\site-packages\apscheduler\job.py", line 175, in _modify
    check_callable_args(func, args, kwargs)
  File "D:\Python27\lib\site-packages\apscheduler\util.py", line 367, in check_callable_args
    ', '.join(unsatisfied_args))
ValueError: The following arguments have not been supplied: name
```

![image](https://user-images.githubusercontent.com/3938751/33119424-f5f3f1d0-cfa9-11e7-972d-36636c3522c1.png)

I don't understand this check meaning. 
1.  add_job does accept a `name` parameter
2.  flask_apscheduler would add id as name, even if not provide a name , apscheduler would auto generate one as I saw.

Why check this ?  kwargs is empty
```
    unsatisfied_kwargs = []  # keyword-only arguments that don't have a match in kwargs
```

**Comment by agronholm** [comment]
It would help a lot if you included:

1. the signature of the target function
1. the complete list of actual arguments passed to `add_job()`

**Comment by eromoe** [comment]
1. 
```
sig.parameters
Out[3]: OrderedDict([('name', <Parameter at 0x61c74e0 'name'>)])
func
Out[4]: <function scheduler.jobs.bid.test_writefile>
```

2.  
```
{'func': <function scheduler.jobs.bid.test_writefile>,
 'id': u'1',
 'name': u'1',
 u'seconds': 10,
 'trigger': u'interval'}
```

**Comment by agronholm** [comment]
So are you passing it the `name` argument when scheduling it?

**Comment by eromoe** [comment]
I didn't,  but flask_apscheduler did it

My code:
```
job = current_app.apscheduler.add_job(order['id'], func, name=order['id'], trigger=order['trigger'],**params)
```

flask_apscheduler 's  code
```
    def add_job(self, id, func, **kwargs):
        """
        Add the given job to the job list and wakes up the scheduler if it's already running.

        :param str id: explicit identifier for the job (for modifying it later)
        :param func: callable (or a textual reference to one) to run at the given time
        """

        job_def = dict(kwargs)
        job_def['id'] = id
        job_def['func'] = func
        job_def['name'] = job_def.get('name') or id

        fix_job_def(job_def)

        return self._scheduler.add_job(**job_def)
```

`self._scheduler` is <apscheduler.schedulers.background.BackgroundScheduler object at 0x04BF2A10>

**Comment by agronholm** [comment]
You are misunderstanding something. `job_def['name']` is something that's passed to `add_job()`. What you need, however, is to pass a value for the `name` argument in **your target function**. So you need to use either `args` or `kwargs` for that.

**Comment by eromoe** [comment]
Oh, my bad. I forgot the test function require a argument ...
