### ISSUE TITLE
Tornado5.0 executor RuntimeError: There is no current event loop in thread

### ISSUE THREAD

**Issue by pyclear** [agronholm/apscheduler#307]
TornadoScheduler not run tornado 5.0,  executor have RuntimeError.  [tornadoweb/tornado/issuses/2183](https://github.com/tornadoweb/tornado/issues/2183#issuecomment-371001254)

**Comment by agronholm** [comment]
Tests pass on the latest Tornado version. Can you provide a script to reproduce the problem?

**Comment by pyclear** [comment]
ok ,this is [my test code](https://gist.github.com/pyclear/07563132c780b1febea05214c35dd515)
and this is [my pipfile](https://gist.github.com/pyclear/d9c20ff0bc16fae16c97de815fb8984b)

**Comment by pyclear** [comment]
**there is my run Trackback:**
Press Ctrl+C to exit
ERROR:apscheduler.executors.default:Job "send_msg (trigger: interval[0:00:03], next run at: 2018-05-23 10:32:17 CST)" raised an exception
Traceback (most recent call last):
  File "/Users/Pyclear/.local/share/virtualenvs/miniprogram-q2gB8wwl/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/Pyclear/.local/share/virtualenvs/miniprogram-q2gB8wwl/lib/python3.6/site-packages/tornado/gen.py", line 288, in wrapper
    future = _create_future()
  File "/Users/Pyclear/.local/share/virtualenvs/miniprogram-q2gB8wwl/lib/python3.6/site-packages/tornado/gen.py", line 186, in _create_future
    future = Future()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 678, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread '<concurrent.futures.thread.ThreadPoolExecutor object at 0x105305588>_1'.
ERROR:apscheduler.executors.default:Job "producer (trigger: interval[0:00:03], next run at: 2018-05-23 10:32:17 CST)" raised an exception
Traceback (most recent call last):
  File "/Users/Pyclear/.local/share/virtualenvs/miniprogram-q2gB8wwl/lib/python3.6/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/Pyclear/.local/share/virtualenvs/miniprogram-q2gB8wwl/lib/python3.6/site-packages/tornado/gen.py", line 288, in wrapper
    future = _create_future()
  File "/Users/Pyclear/.local/share/virtualenvs/miniprogram-q2gB8wwl/lib/python3.6/site-packages/tornado/gen.py", line 186, in _create_future
    future = Future()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 678, in get_event_loop
    return get_event_loop_policy().get_event_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 584, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread '<concurrent.futures.thread.ThreadPoolExecutor object at 0x105305588>_0'.

**Comment by agronholm** [comment]
This is because APScheduler starts all tasks in worker threads. Only AsyncIOScheduler supports coroutines, and only then using the native syntax (`async def`).

**Comment by pyclear** [comment]
`Only AsyncIOScheduler supports coroutines`,  you mean APScheduler   current version？ em，Because  same the way using tornado on 4.5 version and APScheduler before。

**Comment by pyclear** [comment]
Because Tornado5.0 default asyncio, so on 5.0. using AsyncIOScheduler is right way. Thank you very much.  🎉
