### ISSUE TITLE
Unable to pass value to function

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#31]
Using Python 2.7.2  -Trying to pass a value to the function that add_cron_job calls. Errors out.

    
    #!python
    from apscheduler.scheduler import Scheduler
    
    sched = Scheduler()
    sched.start()
    
    jobid=2
    
    def run_job(n):
    	print "Running Job: ", n
    
    def run_job2():
    	print "Running Job without passing ID "
    
    # Trying to pass a value to the function fails with "TypeError: func must be callable"
    sched.add_cron_job(run_job(jobid),  minute='*/5')
    
    # Not passing a value
    sched.add_cron_job(run_job2,  minute='*/5')
    
    sched.print_jobs()
    
    

Error:
Traceback (most recent call last):
  File "schedual.py", line 17, in <module>
    sched.add_cron_job(run_job(2),  minute='*/5')
  File "c:\sw_nt\python27\lib\site-packages\apscheduler\scheduler.py", line 347,
 in add_cron_job
    return self.add_job(trigger, func, args, kwargs, **options)
  File "c:\sw_nt\python27\lib\site-packages\apscheduler\scheduler.py", line 258,
 in add_job
    options.pop('coalesce', self.coalesce), **options)
  File "c:\sw_nt\python27\lib\site-packages\apscheduler\job.py", line 44, in __i
nit__
    raise TypeError('func must be callable')
TypeError: func must be callable

----------------------------------------
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/15
- Originally reported by: Anonymous
- Originally created at: 2011-09-26T21:37:33.061

**Comment by agronholm** [comment]
So you are running the run_job() function with a single argument (jobid) and passing the result to add_cron_job() and you expect it to work?

----------------------------------------
Original comment by: Alex Grönholm

**Comment by agronholm** [comment]
Hello Alex,

I'm new to APScheduler... and I'm encountering the same issue that "anonymous" is attempting to overcome.

I had the same line of thinking... However it is obviously wrong.

Can you please explain how you'd go about passing parameters to  a job_function; or point me to the appropriate documentation?

Thank you.

--Mike

----------------------------------------
Original comment by: Michael  Bogucki

**Comment by agronholm** [comment]
Hello Alex,

D'oh..it figures that after I ask the question, I discover the answer. 

add_cron_job(run_job, args=[jobid], minute='*/5')

Thank you.

----------------------------------------
Original comment by: Michael  Bogucki
