### ISSUE TITLE
jobstores default redis

### ISSUE THREAD

**Issue by wuyazibest** [agronholm/apscheduler#353]
```python
import time
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.redis import RedisJobStore
from apscheduler.executors.pool import ThreadPoolExecutor

class SchedulerTask():
    def __init__(self):
        jobstores = {
            "default": RedisJobStore(host="localhost", port=6379, db=13)  # 存储器
            # "default": SQLAlchemyJobStore(url='sqlite:///jobs.sqlite') # 存储器
        }
        executors = {
            "default": ThreadPoolExecutor(10)  # 最大线程数
        }
        job_defaults = {
            "coalesce": False,
            "max_instances": 5  # 最大作业实例数
        }

        scheduler = BackgroundScheduler(jobstores=jobstores, executors=executors, 
                                                                job_defaults=job_defaults)
        scheduler.start()
        self.app = scheduler

     def add_task(self):
        self.app.add_job(my_job_1,id="job_1",trigger="interval",seconds=3)  # 每5分钟执行一次
        self.app.add_job(my_job_2,id="job_3",trigger="interval",seconds=3)  # 每5分钟执行一次
        self.app.add_job(my_job_2,id="job_2",trigger="cron",hour=0,minute=3)   # 每天0点过5分执行一次

    def modify_task(self, job_id="job_1", time=5):
        self.app.reschedule_job(job_id, trigger="interval", seconds=time)

    def remove_task(self, job_id="job_1"):
        self.app.remove_job(job_id)

    def remove_all_task(self):
        self.app.remove_all_jobs()


def my_job_1():
    print("job start working")

def my_job_2():
    print("job two start working")

if __name__ == '__main__':
    app = SchedulerTask()
    app.add_task()
    time.sleep(5)
    app.modify_task(time=1)
    time.sleep(5)
    app.remove_task()
    time.sleep(5)
    app.remove_all_task()
```

error message:

```
Traceback (most recent call last):
  File "/home/wu/PythonDevelop/exercise/apscheduler_task/main.py", line 69, in <module>
    app.add_task()
  File "/home/wu/PythonDevelop/exercise/apscheduler_task/main.py", line 45, in add_task
    self.app.add_job(my_job_1,id="job_1",trigger="interval",seconds=3)  # 每5分钟执行一次
  File "/home/wu/.virtualenvs/py3.5_devlop/lib/python3.5/site-packages/apscheduler/schedulers/base.py", line 439, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/home/wu/.virtualenvs/py3.5_devlop/lib/python3.5/site-packages/apscheduler/schedulers/base.py", line 864, in _real_add_job
    store.add_job(job)
  File "/home/wu/.virtualenvs/py3.5_devlop/lib/python3.5/site-packages/apscheduler/jobstores/redis.py", line 84, in add_job
    pipe.zadd(self.run_times_key, datetime_to_utc_timestamp(job.next_run_time), job.id)
  File "/home/wu/.virtualenvs/py3.5_devlop/lib/python3.5/site-packages/redis/client.py", line 2263, in zadd
    for pair in iteritems(mapping):
  File "/home/wu/.virtualenvs/py3.5_devlop/lib/python3.5/site-packages/redis/_compat.py", line 123, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'
```

Process finished with exit code 1

if me use   "default": SQLAlchemyJobStore(url='sqlite:///jobs.sqlite')    the successful
but me use "default": RedisJobStore()    is fail

I hope everyone can understand what I said.
thank all very much

**Comment by agronholm** [comment]
It is possible that an updated version of the redis library has broken backwards compatibility.

**Comment by wuyazibest** [comment]
> It is possible that an updated version of the redis library has broken backwards compatibility.

Thank you very much, my redis server version is 3.2.8  
the python environment reids version redis==3.0.1    i will change this version  look at the results again

**Comment by agronholm** [comment]
I can probably take a look at how the latest redis library works with apscheduler today.

**Comment by tornikenats** [comment]
Any update on how to deal with this?

**Comment by agronholm** [comment]
@tornikenats I was unable to reproduce this with the latest redis version and the latest Python redis library. Can you specify which version of the Redis server you're having difficulties with? Are you using the latest version of the Python redis library?

**Comment by tornikenats** [comment]
@agronholm The Redis version I was using was outdated. I'll post back if the issue returns.
