### ISSUE TITLE
Exception at Redis job store.

### ISSUE THREAD

**Issue by losywee** [agronholm/apscheduler#365]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

## Expected Behavior

Traceback (most recent call last):
  File "scheduler.py", line 18, in <module>
    scheduler.start()
  File "/lib/python3.7/site-packages/apscheduler/schedulers/background.py", line 33, in start
    BaseScheduler.start(self, *args, **kwargs)
  File "/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 158, in start
    self._real_add_job(job, jobstore_alias, replace_existing)
  File "/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 864, in _real_add_job
    store.add_job(job)
  File "/lib/python3.7/site-packages/apscheduler/jobstores/redis.py", line 84, in add_job
    pipe.zadd(self.run_times_key, datetime_to_utc_timestamp(job.next_run_time), job.id)
  File "/lib/python3.7/site-packages/redis/client.py", line 2320, in zadd
    for pair in iteritems(mapping):
  File "/lib/python3.7/site-packages/redis/_compat.py", line 109, in iteritems
    return iter(x.items())
AttributeError: 'float' object has no attribute 'items'

## Steps to Reproduce

1.
2.
3.
4.

## Context (Environment)

1. Python 3.7.2 
2. apscheduler:latest
3. redis:latest ( Redis client library )
4. redis-server ( All version had tested. )

**Comment by losywee** [comment]
Solved:  Replace redis module of 2.10.6.

pip install redis==2.10.6

**Comment by agronholm** [comment]
Are you saying that you fixed the problem by installing an older version of the redis client? I just tested and the tests pass with latest redis client and server combination.

**Comment by agronholm** [comment]
Right, this happens because I have not yet released the updated code which works with the latest version of the redis library.

**Comment by agronholm** [comment]
@losywee I've now release APScheduler 3.6.0 which works with the latest redis library.

**Comment by losywee** [comment]
@agronholm  Thanks very much.
