### ISSUE TITLE
[Bug] TImezone <StaticTzInfo 'local'> can not be feed into `BackgroundScheduler` as timezone

### ISSUE THREAD

**Issue by johnklee** [agronholm/apscheduler#400]
## Expected Behavior
Check below sample code:
```
>>> from tzlocal import get_localzone
>>> import apscheduler
>>> from apscheduler.schedulers.background import BackgroundScheduler
>>> localzone = get_localzone()
>>> localzone
<StaticTzInfo 'local'>
>>> scheduler = BackgroundScheduler(timezone=localzone)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/base.py", line 126, in configure
    self._configure(config)
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/util.py", line 87, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).
```
The exception is not expected and the class `BackgroundScheduler` should be able to handle any kind of time zone returned by [`get_localzone()`](https://github.com/regebro/tzlocal/blob/master/tzlocal/unix.py)

## Current Behavior
With timezone=`<StaticTzInfo 'local'>`, code as `scheduler = BackgroundScheduler(timezone=localzone)` will throw exception

## Steps to Reproduce
Check sample code below:
```
>>> from tzlocal import get_localzone
>>> import apscheduler
>>> from apscheduler.schedulers.background import BackgroundScheduler
>>> localzone = get_localzone()
>>> localzone
<StaticTzInfo 'local'>
>>> scheduler = BackgroundScheduler(timezone=localzone)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/base.py", line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/base.py", line 126, in configure
    self._configure(config)
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/background.py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/schedulers/base.py", line 697, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib64/python3.6/site-packages/apscheduler/util.py", line 87, in astimezone
    'Unable to determine the name of the local timezone -- you must explicitly '
ValueError: Unable to determine the name of the local timezone -- you must explicitly specify the name of the local timezone. Please refrain from using timezones like EST to prevent problems with daylight saving time. Instead, use a locale based timezone name (such as Europe/Helsinki).
>>> localzone.zone
'local'
```

**Comment by agronholm** [comment]
This is not a bug – APScheduler needs an explicit timezone name. That is what the error message is all about. What Linux distribution are you running?

**Comment by agronholm** [comment]
I'm asking because the tzlocal package employs all kinds of tricks to figure out the local timezone, but it can fail if the distribution is uncooperative and does not expose the name of the local timezone anywhere. Are you sure you have the latest version of that too?

**Comment by johnklee** [comment]
Hi @agronholm ,
With command `uname`, the Linux distribution of container is:
```console
bash-4.4$ uname -a
Linux 3ce60ab533d5 3.10.0-1062.1.1.el7.x86_64 #1 SMP Tue Aug 13 18:39:59 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

bash-4.4$ date +"%Z %z"
UTC +0000
```
According to the command `date`, the timezone of the container is `UTC +0000`. Currently we just work around this issue by:
```python
    #
    # Currently, BackgroundScheduler can not handle timezone=<StaticTzInfo 'local'> (UTC)
    # There is a issue to track this problem:
    # https://github.com/agronholm/apscheduler/issues/400
    # When above issue is resolved, we can rewrite below code to avoid try/except
    #
    localzone = get_localzone()
    log.info('localzone={}'.format(localzone))
    try:
        scheduler = BackgroundScheduler(timezone=localzone)
    except:
        scheduler = BackgroundScheduler(timezone=localzone._tzname)
```
For the exception clause:
```python
>>> from tzlocal import get_localzone
>>> localzone = get_localzone()
>>> localzone._tzname
'UTC'
```
The version of tzlocal:
```
bash-4.4$ pip freeze | grep tzlocal
tzlocal==2.0.0
```
The point here is that we don't expect to handle the exception here. For the package more friendly to us, it should cover the trick by inside the package. Any comment or suggestion is appreciated.

**Comment by agronholm** [comment]
You're not supposed to handle the exception. The exception is there to tell you that explicit configuration is necessary because APScheduler cannot guess the correct value for you. Based on the kernel version the Linux version is really ancient, to the point that tzlocal might not work properly with it.
