### ISSUE TITLE
Logging throws error with Gunicorn

### ISSUE THREAD

**Issue by jeffin-ntx** [agronholm/apscheduler#457]
This issue tracker is **ONLY** for reporting bugs.
Issues other than bug reports will be summarily closed.

Any support questions or feature requests should be directed to:

* [StackOverflow](http://stackoverflow.com/questions/tagged/apscheduler)
* [Gitter](https://gitter.im/apscheduler/Lobby)
* [Google groups](http://groups.google.com/group/apscheduler)

## Expected Behavior

Log statements work same in both development and production mode

## Current Behavior
The first time a job is throw logger throws and error but subsequent use of that line doesn't 

## Steps to Reproduce

1. Create a minimal flask app
2. USe APS to add 2 jobs
3. Use gunicorn and redirect the app logs
4. The logs when used with gunicorn throws error , everything works smooth when you use `python run.py`, the only issus is that the first time `  self._logger.info('Added job "%s" to job store "%s"', job.name, jobstore_alias)` throws error but subsequent use of that line doesn't 

## Context (Environment)

Flask app with apscheduler
Basic logger used
```
dictConfig(
    {
        "version": 1,
        "formatters": {
            "default": {
                "format": "[%(asctime)s] %(levelname)s in %(module)s: %(message)s",
            }
        },
        "handlers": {
            "wsgi": {
                "class": "logging.StreamHandler",
                "stream": "ext://flask.logging.wsgi_errors_stream",
                "formatter": "default",
            }
        },
        "root": {"level": "INFO", "handlers": ["wsgi"]},
    }
)

gunicorn_logger = logging.getLogger('gunicorn.error')

app.logger.handlers = gunicorn_logger.handlers
app.logger.setLevel(gunicorn_logger.level)
```

## Detailed Description

--- Logging error ---
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1037, in emit
    stream.write(msg + self.terminator)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/http/wsgi.py", line 62, in write
    stream.write(data)
AttributeError: 'NoneType' object has no attribute 'write'
Call stack:
  File "/Users/jeffin-ntx/Documents/dr-test-env/bin/gunicorn", line 10, in <module>
    sys.exit(run())
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
    super().run()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 202, in run
    self.manage_workers()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 545, in manage_workers
    self.spawn_workers()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 616, in spawn_workers
    self.spawn_worker()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/workers/base.py", line 140, in init_process
    self.run()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 123, in run
    self.run_for_one(timeout)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 67, in run_for_one
    self.accept(listener)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 29, in accept
    self.handle(listener, client, addr)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask_restful/__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/flask_restful/__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/jeffin-ntx/Documents/xi-test-fail-over-portal/backend/src/jobs.py", line 129, in post
    scheduler_object.addjob(ScheduleJob, args = [TennantUuid,JobName, StartDate, EndDate], trigger='date', run_date= date)
  File "/Users/jeffin-ntx/Documents/xi-test-fail-over-portal/backend/src/scheduler.py", line 70, in addjob
    job = scheduler.add_job(*args, **kwargs)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 443, in add_job
    self._real_add_job(job, jobstore, replace_existing)
  File "/Users/jeffin-ntx/Documents/dr-test-env/lib/python3.7/site-packages/apscheduler/schedulers/base.py", line 881, in _real_add_job
    self._logger.info('Added job "%s" to job store "%s"', job.name, jobstore_alias)
Message: 'Added job "%s" to job store "%s"'
Arguments: ('ScheduleJob', 'default')
[2020-09-15 11:53:59,480] INFO in base: Running job "ScheduleJob (trigger: date[2020-09-15 06:23:59 UTC], next run at: 2020-09-15 06:23:59 UTC)" (scheduled at 2020-09-15 06:23:59.392428+00:00)
[2020-09-15 11:53:59,528] INFO in base: Removed job ae8d0a8807a24e84a2288c0780654d44
[2020-09-15 11:53:59,534] INFO in base: Added job "Worker.ExecuteJob" to job store "default"
[2020-09-15 11:53:59,543] INFO in base: Job "ScheduleJob (trigger: date[2020-09-15 06:23:59 UTC], next run at: 2020-09-15 06:23:59 UTC)" executed successfully
<img width="1419" alt="Screenshot 2020-09-16 at 10 45 22 AM" src="https://user-images.githubusercontent.com/59605042/93295175-142bd600-f80a-11ea-89d1-ef35d99a327e.png">

**Comment by jeffin-ntx** [comment]
Some debugging steps

Added few print statments

<img width="771" alt="Screenshot 2020-09-16 at 10 59 33 AM" src="https://user-images.githubusercontent.com/59605042/93295909-bd270080-f80b-11ea-8c87-249ebe9652f6.png">


Added job  12032943 default
<Logger apscheduler.scheduler (INFO)>

Everything works fine

**Comment by agronholm** [comment]
Why do you think this is anything but a problem with your logging configuration? Does something in the traceback point to an APScheduler bug?

**Comment by jeffin-ntx** [comment]
You are correct, this is a problem with the logger and nothing related to apscheduler, the is flask with blueprint and logger were conflicting 

Thanks
