### ISSUE TITLE
apscheduler causes app to go down (heroku)

### ISSUE THREAD

**Issue by Kenan7** [agronholm/apscheduler#486]
INFO:apscheduler.scheduler:Scheduler started
2021-01-30T06:24:14.779624+00:00 app[web.1]: DEBUG:apscheduler.scheduler:Looking for jobs to run
2021-01-30T06:24:14.827434+00:00 app[web.1]: ERROR:apscheduler.jobstores.default:Unable to restore job "b'job_declared'" -- removing it
2021-01-30T06:24:14.827435+00:00 app[web.1]: Traceback (most recent call last):
2021-01-30T06:24:14.827436+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/apscheduler/jobstores/redis.py", line 135, in _reconstitute_jobs
2021-01-30T06:24:14.827436+00:00 app[web.1]:     jobs.append(self._reconstitute_job(job_state))
2021-01-30T06:24:14.827438+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/apscheduler/jobstores/redis.py", line 123, in _reconstitute_job
2021-01-30T06:24:14.827439+00:00 app[web.1]:     job_state = pickle.loads(job_state)
2021-01-30T06:24:14.827439+00:00 app[web.1]: TypeError: a bytes-like object is required, not 'NoneType'
2021-01-30T06:24:14.876523+00:00 app[web.1]: DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
2021-01-30T06:24:14.899945+00:00 app[web.1]: INFO:apscheduler.scheduler:Added job "job_declared" to job store "default"
2021-01-30T06:24:14.900278+00:00 app[web.1]: DEBUG:apscheduler.scheduler:Looking for jobs to run

**Comment by agronholm** [comment]
Was the bug template unclear? I need a way to reproduce the problem, otherwise I cannot investigate.

**Comment by GabrieleCalarota** [comment]
@Kenan7 are you using gunicorn??
Because I think I had the same problem with apscheduler and gunicorn with requests going in 502 (timeout)

**Comment by agronholm** [comment]
20 months and no response – closing.
