### ISSUE TITLE
ModuleNotFoundError: No module named 'apscheduler'

### ISSUE THREAD

**Issue by zhaojunqin93** [agronholm/apscheduler#489]
Hi there, it might be a silly question.

I have no idea about why I am facing ModuleNotFoundError: No module named 'apscheduler' but I have already successfully installed APscheduler.

I have tried uninstalling it and re-install the specific version of APscheduler, but it didn't work. I also tried installing it on virtualenv, but it didn't work as well.

Python: | pip: 20.3.3 | version: 3.7.3 OS: Linux (Ubuntu 20.04)

```python3
from __future__ import absolute_import
import octoprint.plugin
from apscheduler.schedulers.background import BackgroundScheduler

from influxdb_client import InfluxDBClient, Point
import requests

def __init__(self):
    super().__init__()
    self.backgroundScheduler = BackgroundScheduler()
```
Log information as follows:

> Traceback (most recent call last):
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 1298, in _import_plugin
    module = _load_module(module_name, spec)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/plugin/core.py", line 69, in _load_module
    return imp.load_module(name, f, filename, details)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 238, in load_module
    return load_package(name, filename)
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint/vendor/imp.py", line 212, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/pi/oprint/lib/python3.7/site-packages/octoprint_CMfgDataAcquisition/__init__.py", line 13, in <module>
    from apscheduler.schedulers.background import BackgroundScheduler
ModuleNotFoundError: No module named 'apscheduler'

APscheduler == 3.6.3 has been installed.
![image](https://user-images.githubusercontent.com/77723692/107846664-4d648280-6e4a-11eb-871b-cc876a6563d7.png)

Really appreciate your help!

Cheers

**Comment by agronholm** [comment]
Did you look at the paths in the `pip` output? That command installed them in Python 3.8, and you're trying to use it from Python 3.7. Try `python3.7 -m pip install apscheduler`.

**Comment by agronholm** [comment]
Also, you created this issue as a feature request instead of using the proper channels to ask a question. Please refrain from doing so in the future.
