### ISSUE TITLE
client/server RPyC example does not work when providing `kwargs={...}`

### ISSUE THREAD

**Issue by caffeinatedMike** [agronholm/apscheduler#527]
**Describe the bug**
When using the [RPyC service example](https://github.com/agronholm/apscheduler/tree/master/examples/rpc) to run the scheduler it is not possible to explicitly pass the `kwargs` field to the scheduler (`kwargs` which are supposed to be passed to `func`)

**To Reproduce**
```python3
# server.py
import rpyc
from rpyc.utils.server import ThreadedServer


def print_text(text, test=False):
    print("%s (%r)" % (text, test))


class SchedulerService(rpyc.Service):
    def exposed_add_job(self, func, *args, **kwargs):
        return scheduler.add_job(func, *args, **kwargs)

    def exposed_modify_job(self, job_id, jobstore=None, **changes):
        return scheduler.modify_job(job_id, jobstore, **changes)

    def exposed_reschedule_job(self, job_id, jobstore=None, trigger=None, **trigger_args):
        return scheduler.reschedule_job(job_id, jobstore, trigger, **trigger_args)

    def exposed_pause_job(self, job_id, jobstore=None):
        return scheduler.pause_job(job_id, jobstore)

    def exposed_resume_job(self, job_id, jobstore=None):
        return scheduler.resume_job(job_id, jobstore)

    def exposed_remove_job(self, job_id, jobstore=None):
        scheduler.remove_job(job_id, jobstore)

    def exposed_get_job(self, job_id):
        return scheduler.get_job(job_id)

    def exposed_get_jobs(self, jobstore=None):
        return scheduler.get_jobs(jobstore)


if __name__ == "__main__":
    from apscheduler.schedulers.background import BackgroundScheduler
    scheduler = BackgroundScheduler()
    scheduler.start()
    server = ThreadedServer(SchedulerService, port=12345, protocol_config={"allow_public_attrs": True})
    try:
        server.start()
    except (KeyboardInterrupt, SystemExit):
        pass
    finally:
        scheduler.shutdown()
```
```python3
# client.py
from time import sleep
import rpyc

conn = rpyc.connect('localhost', 12345)
job = conn.root.add_job("server:print_text", "interval", args=["Hello, World"], kwargs={"test": True}, seconds=2)
sleep(10)
conn.root.remove_job(job.id)
```

**Expected behavior**
`kwargs` should be passed to the underlying task

**Additional context**
Traceback describing the issue
```
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
========== RESTART: C:\Users\mhill\PycharmProjects\client.py =========
Traceback (most recent call last):
  File "C:\Users\mhill\PycharmProjects\client.py", line 14, in <module>
    job = conn.root.add_job('server:print_text', 'interval', args=['Hello, World'], kwargs={'test': True}, seconds=2)
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\netref.py", line 240, in __call__
    return syncreq(_self, consts.HANDLE_CALL, args, kwargs)
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\netref.py", line 63, in syncreq
    return conn.sync_request(handler, proxy, *args)
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\protocol.py", line 473, in sync_request
    return self.async_request(handler, *args, timeout=timeout).value
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\async_.py", line 102, in value
    raise self._obj
_get_exception_class.<locals>.Derived: dictionary update sequence element #0 has length 4; 2 is required

========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\protocol.py", line 324, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\rpyc\core\protocol.py", line 592, in _handle_call
    return obj(*args, **dict(kwargs))
  File "C:\Users\mhill\PycharmProjects\server.py", line 29, in exposed_add_job
    return scheduler.add_job(func, *args, **kwargs)
  File "C:\Users\mhill\AppData\Local\Programs\Python\Python37\lib\site-packages\apscheduler\schedulers\base.py", line 429, in add_job
    'kwargs': dict(kwargs) if kwargs is not None else {},
ValueError: dictionary update sequence element #0 has length 4; 2 is required
```

**Current Workaround**
Thanks to [this answer](https://groups.google.com/g/rpyc/c/5WodVPFVXGc/m/4f09fgoEZPMJ) in the rpyc google group we can get around this limitation by explicitly using `pickle.dumps` on the client-side and `pickle.loads` on the server-side whenever `kwargs` is present.
```python
# server.py
import pickle

def print_text(text, test=False):
    print("%s (%r)" % (text, test))


class SchedulerService(rpyc.Service):
    @staticmethod
    def unpickle(kwargs):
        return {key: pickle.loads(value) if isinstance(value, bytes) else value for key, value in kwargs.items()}

    def exposed_add_job(self, func, *args, **kwargs):
        return scheduler.add_job(func, *args, **self.unpickle(kwargs))
...
# rest of the code remains the same
```
```python3
# client.py
from time import sleep
import pickle
import rpyc

conn = rpyc.connect('localhost', 12345)
job = conn.root.add_job('server:print_text', 'interval', args=['Hello, World'], kwargs=pickle.dumps({'test': True}), seconds=2)
sleep(10)
conn.root.remove_job(job.id)
```

**Comment by agronholm** [comment]
What I think happens here is that `dict(kwargs)` does not see `kwargs` as a dict so it's treating it as an iterable instead. That means RPyC is the culprit here.

**Comment by agronholm** [comment]
Confirmed. The easiest workaround is to supply kwargs as a list of items (`[('test', True)]`). I'm not sure what the proper workaround would be here since this is a problem specific to RPyC.

**Comment by caffeinatedMike** [comment]
@agronholm You are correct, it is an RPyC issue. However, I think either:
a) the server/client example should be updated to show this behavior
b) the docs should be updated to state this potential hiccup with `kwargs` while implementing an RPC server only for the fact that:
1) You provide an example of utilizing an RPC service to temporarily circumvent the multi-worker issue as a holdover solution until v4.0
2) Because `kwargs` is a commonly used field when scheduling tasks.

**Note:** I did add a staticmethod to the service in my example. This seems cleanest in terms of server-side. In terms of client-side, I think mentioning the hiccup in the docs would be enough.

**Comment by agronholm** [comment]
I don't think I have the bandwidth to fix or work around RPyC issues anymore, now with 4.0.0a1 out.
