### ISSUE TITLE
Some strange error

### ISSUE THREAD

**Issue by sachoker** [agronholm/apscheduler#531]
I'm try to repeat example from user guide and see strange error

`from time import sleep
from apscheduler.schedulers.background import BackgroundScheduler
from requests import get
def req(i):
    data = get(f"https://reqres.in/api/users/{i}").json()
    print(data)
sched = BackgroundScheduler(daemon=True)
sched.start()
job = sched.add_job(req, 'interval', seconds=5)
while True:
    sleep(2)
    print(1)
    sleep(2)`

and I got this error
`Traceback (most recent call last):
  File "C:\Users\mv149\PycharmProjects\AvitoBotSite\Bot\test.py", line 13, in <module>
    job = sched.add_job(req, 'interval', seconds=5)
  File "C:\Users\mv149\PycharmProjects\AvitoBotSite\venv\lib\site-packages\apscheduler\schedulers\base.py", line 439, in add_job
    job = Job(self, **job_kwargs)
  File "C:\Users\mv149\PycharmProjects\AvitoBotSite\venv\lib\site-packages\apscheduler\job.py", line 49, in __init__
    self._modify(id=id or uuid4().hex, **kwargs)
  File "C:\Users\mv149\PycharmProjects\AvitoBotSite\venv\lib\site-packages\apscheduler\job.py", line 180, in _modify
    check_callable_args(func, args, kwargs)
  File "C:\Users\mv149\PycharmProjects\AvitoBotSite\venv\lib\site-packages\apscheduler\util.py", line 405, in check_callable_args
    raise ValueError('The following arguments have not been supplied: %s' %
ValueError: The following arguments have not been supplied: i`

**Comment by agronholm** [comment]
It is as the error says: the "i" argument has not been supplied. What do you think the value of `i` should be in the `req()` function when it's called?

**Comment by agronholm** [comment]
(Also, in the future, please format your code properly)

**Comment by sachoker** [comment]
Ou, so stupid....
Sorry)
