### ISSUE TITLE
block_scheduler raise error

### ISSUE THREAD

**Issue by CGpythoner** [agronholm/apscheduler#532]
**block_scheduler_test.py**

from apscheduler.schedulers.blocking import BlockingScheduler
import click

def print_hello():
    print("hello, --")

@click.command()
@click.option('--hour', help='时间', required=False)
@click.option('--seconds', help='miao', required=False)

def test_case(seconds, hour=None):
    sched = BlockingScheduler()
    sched.add_job(print_hello, 'interval', hour=hour, seconds=int(seconds))
    sched.start()

if __name__ == '__main__':
    test_case()

**error info **
Traceback (most recent call last):
  File "block_scheduler_test.py", line 29, in <module>
    test_case()
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "block_scheduler_test.py", line 23, in test_case
    sched.add_job(print_hello, 'interval', hour=hour, seconds=int(seconds))
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 425, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 926, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/home/pangqiu/.pyenv/versions/3.6.8/envs/pyenv_368/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 911, in _create_plugin_instance
    return plugin_cls(**constructor_kwargs)
TypeError: __init__() got an unexpected keyword argument 'hour'

**info**
python==3.6.8
APScheduler==3.7.0
click==7.1.2

**Comment by agronholm** [comment]
I think you meant "hours" not "hour".

**Comment by CGpythoner** [comment]
> I think you meant "hours" not "hour".

thanks !!!
