### ISSUE TITLE
No application found. Either work inside a view function or push an application context

### ISSUE THREAD

**Issue by yuyecreus** [agronholm/apscheduler#535]
Hello guys!

I am using apscheduler in a flask application and I have deployed it to heroku successfully. I have a "hello world" task to run every minute and it is triggered correctly. However, when I want this task to insert data to the flask SQLAlchemy databse i get the following error in the heroku logs:

```
Job "timed_job (trigger: interval[0:01:00], next run at: 2021-08-09 19:08:59 UTC)" raised an exception
2021-08-09T19:07:59.819261+00:00 app[clock.1]: Traceback (most recent call last):
2021-08-09T19:07:59.819262+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1008, in __call__
2021-08-09T19:07:59.819262+00:00 app[clock.1]:     return self.registry[key]
2021-08-09T19:07:59.819263+00:00 app[clock.1]: KeyError: <greenlet.greenlet object at 0x7f587dc93ca0 (otid=0x7f587ddf6180) current active started main>
2021-08-09T19:07:59.819263+00:00 app[clock.1]: 
2021-08-09T19:07:59.819264+00:00 app[clock.1]: During handling of the above exception, another exception occurred:
2021-08-09T19:07:59.819264+00:00 app[clock.1]: 
2021-08-09T19:07:59.819265+00:00 app[clock.1]: Traceback (most recent call last):
2021-08-09T19:07:59.819265+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
2021-08-09T19:07:59.819265+00:00 app[clock.1]:     retval = job.func(*job.args, **job.kwargs)
2021-08-09T19:07:59.819266+00:00 app[clock.1]:   File "/app/clock.py", line 8, in timed_job
2021-08-09T19:07:59.819266+00:00 app[clock.1]:     my_custom_function("Hello World", 100, 1, 1, True)
2021-08-09T19:07:59.819267+00:00 app[clock.1]:   File "/app/website/utils.py", line 45, in create_new_tournament
2021-08-09T19:07:59.819267+00:00 app[clock.1]:     db.session.add(my_instance)
2021-08-09T19:07:59.819268+00:00 app[clock.1]:   File "<string>", line 2, in add
2021-08-09T19:07:59.819268+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/scoping.py", line 23, in _proxied
2021-08-09T19:07:59.819268+00:00 app[clock.1]:     return self.registry()
2021-08-09T19:07:59.819269+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/util/_collections.py", line 1010, in __call__
2021-08-09T19:07:59.819269+00:00 app[clock.1]:     return self.registry.setdefault(key, self.createfunc())
2021-08-09T19:07:59.819270+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 4101, in __call__
2021-08-09T19:07:59.819270+00:00 app[clock.1]:     return self.class_(**local_kw)
2021-08-09T19:07:59.819270+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 174, in __init__
2021-08-09T19:07:59.819271+00:00 app[clock.1]:     self.app = app = db.get_app()
2021-08-09T19:07:59.819271+00:00 app[clock.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/flask_sqlalchemy/__init__.py", line 1042, in get_app
2021-08-09T19:07:59.819271+00:00 app[clock.1]:     raise RuntimeError(
2021-08-09T19:07:59.819273+00:00 app[clock.1]: RuntimeError: No application found. Either work inside a view function or push an application context. See http://flask-sqlalchemy.pocoo.org/contexts/.
```

What am I doing wrong?

Thank you!

**Comment by agronholm** [comment]
This issue tracker is not for asking questions. The documentation lists the [proper venues](https://apscheduler.readthedocs.io/en/stable/userguide.html#getting-help) for that. I will be happy to answer any questions there if I know the answer.
