### ISSUE TITLE
Doesn't work with "SystemV/PST8" time

### ISSUE THREAD

**Issue by LGabrielson** [agronholm/apscheduler#574]
Our company has decided to use Standard Time all the time now.  I find that APScheduler3 doesn't work when using "SystemV/PST8" time zone.

Traceback (most recent call last):
  File "./recorder_11.py", line 383, in <module>
    sched = BackgroundScheduler()
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/base.py",                                                      line 87, in __init__
    self.configure(gconfig, **options)
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/base.py",                                                      line 131, in configure
    self._configure(config)
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/background                                                     .py", line 29, in _configure
    super(BackgroundScheduler, self)._configure(config)
  File "/usr/local/lib/python3.7/dist-packages/apscheduler/schedulers/base.py",                                                      line 702, in _configure
    self.timezone = astimezone(config.pop('timezone', None)) or get_localzone()
  File "/usr/local/lib/python3.7/dist-packages/tzlocal/unix.py", line 165, in ge                                                     t_localzone
    _cache_tz = _get_localzone()
  File "/usr/local/lib/python3.7/dist-packages/tzlocal/unix.py", line 86, in _ge                                                     t_localzone
    tz = pytz.timezone(etctz.replace(' ', '_'))
  **File "/usr/local/lib/python3.7/dist-packages/pytz/__init__.py", line 181, in t                                                     imezone
    raise UnknownTimeZoneError(zone)**
pytz.exceptions.UnknownTimeZoneError: 'SystemV/PST8'

I'm using APScheduler for dozens of tasks, so if a fix is found, please let me know!  
Thank you.

**Comment by agronholm** [comment]
I've never heard of a time zone like this. Besides, APScheduler does not carry any time zones of its own, it relies on the Olson database within either `pytz`, `tzdata` or the underlying OS itself. Is this tz supposed to be the pacific timezone or something?

**Comment by agronholm** [comment]
Closing due to lack of response.

**Comment by mglowinski93** [comment]
Can we reopen this topic?
I've similar problem with `Europe\Warsaw` timezone.

I've installed `ztdata` package on Ubuntu 20 LTS and set environment variable to `Europe/Warsaw`.
This is what i got afterwards:
```
    return timezone(obj)
  File "/home/SchedulerUser/.local/lib/python3.9/site-packages/pytz/__init__.py", line 188, in timezone
    raise UnknownTimeZoneError(zone)
pytz.exceptions.UnknownTimeZoneError: 'CEST'
```

**Comment by agronholm** [comment]
What environment variable did you set exactly? Did you try that directly with `pytz.timezone()`?

**Comment by mglowinski93** [comment]
I set `TZ` env variable.
I already found my issue.
It was unrelated to this library, but to [flask-apscheduler](https://github.com/viniciuschiele/flask-apscheduler).
It was configured with
```
SCHEDULER_TIMEZONE = time.tzname[time.daylight]
```
instead of 
```
SCHEDULER_TIMEZONE = tzlocal.get_localzone()
```

One i changed that everything started working fine:)
