### ISSUE TITLE
Tornado Multiprocess bug？

### ISSUE THREAD

**Issue by pythonpray** [agronholm/apscheduler#695]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.9.1.post1

### What happened?

if i start project with multiprocess，error info like this.

[2023-01-03 10:41:59] [INFO] [(module)s:31]start omc_server:http://127.0.0.1:8899
[2023-01-03 10:41:59] [INFO] [(module)s:444] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2023-01-03 10:41:59,610] - INFO - /Users/fengbo/PycharmProjects/datamanager/cron_task/scheduler.py - init_job - 52 - task add success: datamanager/odps/odps.py
[2023-01-03 10:41:59] [INFO] [(module)s:52] task add success: datamanager/odps/odps.py
[2023-01-03 10:41:59] [INFO] [(module)s:444] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2023-01-03 10:41:59,611] - INFO - /Users/fengbo/PycharmProjects/datamanager/cron_task/scheduler.py - init_job - 52 - task add success: datamanager/rds/rds.py
[2023-01-03 10:41:59] [INFO] [(module)s:52] task add success: datamanager/rds/rds.py
[2023-01-03 10:41:59] [INFO] [(module)s:444] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2023-01-03 10:41:59,611] - INFO - /Users/fengbo/PycharmProjects/datamanager/cron_task/scheduler.py - init_job - 52 - task add success: datamanager/ads2/ads2.py
[2023-01-03 10:41:59] [INFO] [(module)s:52] task add success: datamanager/ads2/ads2.py
[2023-01-03 10:41:59] [INFO] [(module)s:444] Adding job tentatively -- it will be properly scheduled when the scheduler starts
[2023-01-03 10:41:59,611] - INFO - /Users/fengbo/PycharmProjects/datamanager/cron_task/scheduler.py - init_job - 52 - task add success: datamanager/crond_task/odps/test.py
[2023-01-03 10:41:59] [INFO] [(module)s:52] task add success: datamanager/crond_task/odps/test.py
/Library/Python/3.9/site-packages/apscheduler/util.py:436: PytzUsageWarning: The localize method is no longer necessary, as this time zone supports the fold attribute (PEP 495). For more details on migrating to a PEP 495-compliant implementation, see https://pytz-deprecation-shim.readthedocs.io/en/latest/migration.html
  return tzinfo.localize(dt)
[2023-01-03 10:41:59] [INFO] [(module)s:885] Added job "odps治理项采集任务" to job store "default"
[2023-01-03 10:41:59] [INFO] [(module)s:885] Added job "rds治理项采集任务" to job store "default"
[2023-01-03 10:41:59] [INFO] [(module)s:885] Added job "ads2治理项采集任务" to job store "default"
[2023-01-03 10:41:59] [INFO] [(module)s:885] Added job "test任务" to job store "default"
[2023-01-03 10:41:59] [INFO] [(module)s:171] Scheduler started
[2023-01-03 10:41:59] [INFO] [(module)s:128] Starting 8 processes
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '16 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fengbo/PycharmProjects/datamanager/server.py", line 62, in <module>
    key = self._selector.get_key(fd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    key = self._selector.get_key(fd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '16 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fengbo/PycharmProjects/datamanager/server.py", line 62, in <module>
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '16 is not registered'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/fengbo/PycharmProjects/datamanager/server.py", line 62, in <module>
    main()
  File "/Users/fengbo/PycharmProjects/datamanager/server.py", line 57, in main
    http_server.start(num_processes=num_processes)
  File "/Library/Python/3.9/site-packages/tornado/tcpserver.py", line 222, in start
    main()
  File "/Users/fengbo/PycharmProjects/datamanager/server.py", line 57, in main
    http_server.start(num_processes=num_processes)
  File "/Library/Python/3.9/site-packages/tornado/tcpserver.py", line 222, in start
    self.add_sockets(sockets)
  File "/Library/Python/3.9/site-packages/tornado/tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/Library/Python/3.9/site-packages/tornado/netutil.py", line 268, in add_accept_handler
    main()
  File "/Users/fengbo/PycharmProjects/datamanager/server.py", line 57, in main
    http_server.start(num_processes=num_processes)
  File "/Library/Python/3.9/site-packages/tornado/tcpserver.py", line 222, in start
    self.add_sockets(sockets)
  File "/Library/Python/3.9/site-packages/tornado/tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/Library/Python/3.9/site-packages/tornado/netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/Library/Python/3.9/site-packages/tornado/platform/asyncio.py", line 79, in add_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/Library/Python/3.9/site-packages/tornado/platform/asyncio.py", line 79, in add_handler
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 261, in _add_reader
    self.asyncio_loop.add_reader(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 336, in add_reader
    self.add_sockets(sockets)
  File "/Library/Python/3.9/site-packages/tornado/tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "/Library/Python/3.9/site-packages/tornado/netutil.py", line 268, in add_accept_handler
    self._add_reader(fd, callback, *args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "/Library/Python/3.9/site-packages/tornado/platform/asyncio.py", line 79, in add_handler
    self._selector.register(fd, selectors.EVENT_READ,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 523, in register
    self.asyncio_loop.add_reader(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 336, in add_reader
        self.asyncio_loop.add_reader(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 336, in add_reader
    key = self._selector.get_key(fd)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 193, in get_key
    self._add_reader(fd, callback, *args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._add_reader(fd, callback, *args)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/selector_events.py", line 263, in _add_reader
    self._selector.register(fd, selectors.EVENT_READ,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/selectors.py", line 523, in register
    raise KeyError("{!r} is not registered".format(fileobj)) from None
KeyError: '16 is not registered'self._selector.control([kev], 0, 0)

### How can we reproduce the bug?

import atexit
import fcntl
from apscheduler.schedulers.tornado import TornadoScheduler

scheduler = TornadoScheduler()

def create_scheduler():
    f = open("conf/scheduler.lock", "wb")
    try:
        fcntl.flock(f, fcntl.LOCK_EX | fcntl.LOCK_NB)
        init_job()
        scheduler.start()
    except:
        pass

    def unlock():
        fcntl.flock(f, fcntl.LOCK_UN)
        f.close()

    atexit.register(unlock)
    return scheduler

from tornado import web, ioloop, httpserver, options, log

def make_app():
    app = web.Application(urlpattern, **settings)
    return app

def main(*args, **kwargs):
    logger.info("start omc_server:http://127.0.0.1:{}".format(omc_port))
    for k, v in LOGGING["options"].items():
        options.options.__setattr__(k, v)

    options.parse_command_line()

    formatter = log.LogFormatter(**LOGGING["formatter"])
    [i.setFormatter(formatter) for i in logging.getLogger().handlers]

    # 定时任务初始化
    create_scheduler()

    app = make_app()
    http_server = httpserver.HTTPServer(app)
    http_server.bind(8899)
    http_server.start(num_processes=8)
    ioloop.IOLoop.current().start()

if http_server.start()，num_processes=1 ，it works。
if num_processes>1, it don't works

I try use fcntl module make app just run once，it doesn't work。

**Comment by agronholm** [comment]
So what makes you think this is an APScheduler bug rather than a problem with your locking mechanism?

**Comment by agronholm** [comment]
Closing due to lack of responses.
