### ISSUE TITLE
Issue running job in thread via multiprocess

### ISSUE THREAD

**Issue by dutangp** [agronholm/apscheduler#723]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.1

### What happened?

I am testing apscheduler in a bot application to help me scheduling task in specific datetime. I am running the apscheduler in a via a new thread in a process.

When I am scheduling a new job I have this issue

```
ERROR:apscheduler.scheduler:Error submitting job "test_tasker (trigger: date[2023-03-24 01:55:57 UTC], next run at: 2023-03-24 01:55:57 UTC)" to executor "tasker"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

I have big doubt regarding using threading and I suspect issue with executor but I am not sure, I am currently trying few fix but so far nothing successful.
 

### How can we reproduce the bug?

I wrote a really simple python code that we can run directly in IDE

```
from apscheduler.schedulers.background import BackgroundScheduler
import time
import logging
import datetime
import tzlocal
import sys
import threading
import multiprocessing

logging.basicConfig()
logging.getLogger('apscheduler').setLevel(logging.DEBUG)
numLog = getattr(logging, 'DEBUG')
logger = logging.getLogger('my_app')
logger_handler = logging.StreamHandler(sys.stdout)
logger_format = logging.Formatter(
    '%(asctime)s - %(levelname)s - %(message)s'
)
logger_handler.setFormatter(logger_format)
logger.setLevel(numLog)
logger.addHandler(logger_handler)
logger.info(
    'Logging client initialized successfully as %s', 'DEBUG'
)

executors = {
    'tasker': {'type': 'threadpool', 'max_workers': 20},
}
task_scheduler = BackgroundScheduler(
    executors=executors,
    timezone=str(tzlocal.get_localzone())
)


def test_tasker():
    logger.info('[Tasker] - Test tasker with init job')


def init_tasker():
    date = datetime.datetime.now() + datetime.timedelta(seconds=10)
    """ initiate all jobs and restart daily the scheduler """
    while True:
        logger.info(f'[Tasker] status is {task_scheduler.state}')
        if not task_scheduler.state:
            logger.info('Tasker - Restarting tasker')
            task_scheduler.start()
            if task_scheduler.state:
                task_scheduler.add_job(test_tasker, 'date', executor='tasker', run_date=date)
        time.sleep(5)


def main_scheduler():
    logger.info(f'[Tasker] init tasker')
    # tasker needs to be handle differently in the thread
    tasker = threading.Thread(target=init_tasker)
    tasker.start()

multiprocessing.Process(target=main_scheduler).start()
```

result I have

```
INFO:my_app:[Tasker] init tasker
2023-03-24 01:55:47,681 - INFO - [Tasker] status is 0
INFO:my_app:[Tasker] status is 0
2023-03-24 01:55:47,682 - INFO - Tasker - Restarting tasker
INFO:my_app:Tasker - Restarting tasker
INFO:apscheduler.scheduler:Scheduler started
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
INFO:apscheduler.scheduler:Added job "test_tasker" to job store "default"
DEBUG:apscheduler.scheduler:Looking for jobs to run
DEBUG:apscheduler.scheduler:Next wakeup is due at 2023-03-24 01:55:57.681403+00:00 (in 9.993603 seconds)
2023-03-24 01:55:52,688 - INFO - [Tasker] status is 1
INFO:my_app:[Tasker] status is 1
DEBUG:apscheduler.scheduler:Looking for jobs to run
2023-03-24 01:55:57,690 - INFO - [Tasker] status is 1
ERROR:apscheduler.scheduler:Error submitting job "test_tasker (trigger: date[2023-03-24 01:55:57 UTC], next run at: 2023-03-24 01:55:57 UTC)" to executor "tasker"
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/schedulers/base.py", line 978, in _process_jobs
    executor.submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 169, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
INFO:my_app:[Tasker] status is 1
INFO:apscheduler.scheduler:Removed job 3df3256673dc470eb059870e814967c7
DEBUG:apscheduler.scheduler:No jobs; waiting until a job is added
2023-03-24 01:56:02,696 - INFO - [Tasker] status is 1
INFO:my_app:[Tasker] status is 1
```

ref

```
pip3 show apscheduler
Name: APScheduler
Version: 3.10.1
Summary: In-process task scheduler with Cron-like capabilities
Home-page: https://github.com/agronholm/apscheduler
Author: Alex Grönholm
Author-email: apscheduler@nextday.fi
License: MIT
Location: /usr/local/lib/python3.11/site-packages
Requires: pytz, setuptools, six, tzlocal
Required-by:
```

**Comment by dutangp** [comment]
I have tried without

```
executors = {
    'tasker': {'type': 'threadpool', 'max_workers': 20},
}
```

and I removed the `executor` in `add_job` but I have the same issue

**Comment by dutangp** [comment]
As well I have tried

```
def main_scheduler():
    logger.info(f'[Tasker] init tasker')
    # tasker needs to be handle differently in the thread
    tasker = threading.Thread(target=init_tasker)
    tasker.start()
    tasker.join()
```
it works but I block my process so it's not my goal

**Comment by dutangp** [comment]
found a solution by calling my thread with `concurrent.futures`

**Comment by riosw** [comment]
Possibly this is because the program immediately closes after you `start()`ed the process. Does starting the process like this work as you intended?

```
if __name__ == "__main__":
    process = multiprocessing.Process(target=main_scheduler, daemon=True)
    process.start()
    print("You can do anything here!")
    process.join()  # Waits for the process to be over. Prevents the program from exiting
```

**Comment by dutangp** [comment]
Unfortunately this is not quite works for me, I have a lot happening after calling my `main_scheduler` process. I found a dirty workaround by adding a `while` in my function `main_scheduler` to force the process to not end.

```
def main_scheduler():
    logger.info(f'[Tasker] init tasker')
    # tasker needs to be handle differently in the thread
    threading.Thread(target=init_tasker).start()
    while True:
        time.sleep(60)
```

what is strange is my `main_scheduler()` is calling schedule library and socket library in this `main_scheduler()` function and it doesn't end like it does for `init_tasker`.

**Comment by riosw** [comment]
Sorry, in my previous comment I meant that you should use my code snippet **together with** calling `tasker.join()` in your `main_scheduler` (just like your comment [here](https://github.com/agronholm/apscheduler/issues/723#issuecomment-1482153587)).

Basically, after starting a **subprocess** or a **thread**,  calling an infinite loop (`while True:`) and calling `process/thread.join()` has the same goal: to prevent returning (or stopping) your **parent** process (the one you call `process/thread.start()` on).

I am guessing that your previous errors:
`RuntimeError: cannot schedule new futures after interpreter shutdown` , and
`RuntimeError: can't register atexit after shutdown` 
are caused by the **parent** process returning (stopping) too soon.

Because, when `start()` is called, basically you can imagine that the program 'diverges' into 2: the caller parent process (which immediately dies after `start()` because there is nothing blocking them via infinite loop / `join()`) and the subprocess/thread (where you literally use the scheduler). Weird stuff might happen when the caller/parent process returns before the child does.

Also, if you still need it, please elaborate more on "I have a lot happening after calling my main_scheduler process", because I think that you can do those "a lot" of things after calling the `process.start()`

**Comment by dutangp** [comment]
I understand what you mean, but I am still confused about other thread running in the same process and not dying. I have tried to make a quick example of what I am using

```
from apscheduler.schedulers.background import BackgroundScheduler
import time
import logging
import datetime
import tzlocal
import sys
import threading
import multiprocessing
import schedule

numLog = getattr(logging, 'DEBUG')
logger = logging.getLogger('my_app')
logger_handler = logging.StreamHandler(sys.stdout)
logger_format = logging.Formatter(
    '%(asctime)s - %(levelname)s - %(message)s'
)
logger_handler.setFormatter(logger_format)
logger.setLevel(numLog)
logger.addHandler(logger_handler)
logger.info(
    'Logging client initialized successfully as %s', 'DEBUG'
)

task_scheduler = BackgroundScheduler(
    timezone=str(tzlocal.get_localzone())
)


def scheduler_test():
    logger.info('[Scheduler] - Test scheduler job in dev mode')
    logger.info(f'[Scheduler] - Tasker {task_scheduler.state}')


def test_tasker():
    logger.info('[Tasker] - Test tasker with init job')


def init_tasker():
    """ initiate all jobs and restart daily the scheduler """
    task_scheduler.start()
    while True:
        logger.info(f'[Tasker] status is {task_scheduler.state}')
        date = datetime.datetime.now() + datetime.timedelta(seconds=30)
        task_scheduler.add_job(test_tasker, 'date', run_date=date)
        time.sleep(15)


def init_scheduler():
    """ initiate all jobs and restart daily the scheduler """
    logger.info('[Scheduler] - Dev job - init job')
    schedule.every(30).seconds.do(scheduler_test)
    while True:
        schedule.run_pending()
        if datetime.datetime.now().strftime("%H:%M:%S") == "06:25:00":
            logger.info(
                '[Scheduler] - Restart scheduler for daily '
                'and weekly jobs'
            )
        time.sleep(1)


def main_scheduler():
    logger.info('Scheduler - Start scheduler')
    threading.Thread(target=init_scheduler).start()
    logger.info(f'doing something else in the same time')
    logger.info(f'[Tasker] init tasker')
    threading.Thread(target=init_tasker).start()
    logger.info(f'doing something else in the same time')
    while True:
        time.sleep(60)

multiprocessing.Process(target=main_scheduler).start()
```

here the function `main_scheduler()` is the most important, if you try to different way such as

```
def main_scheduler():
    logger.info('Scheduler - Start scheduler')
    threading.Thread(target=init_scheduler).start()
    logger.info(f'doing something else in the same time')
```
in this case it runs as expected and the thread and process doesn't die as we have `init_schedule` with a loop

```
def main_scheduler():
    logger.info('Scheduler - Start scheduler')
    threading.Thread(target=init_scheduler).start()
    logger.info(f'doing something else in the same time')
    logger.info(f'[Tasker] init tasker')
    threading.Thread(target=init_tasker).start()
    logger.info(f'doing something else in the same time')
```
in this case the tasker die even if `init_tasker` got an infinit loop

```
def main_scheduler():
    logger.info('Scheduler - Start scheduler')
    threading.Thread(target=init_scheduler).start()
    logger.info(f'doing something else in the same time')
    logger.info(f'[Tasker] init tasker')
    threading.Thread(target=init_tasker).start()
    logger.info(f'doing something else in the same time')
    while True:
        time.sleep(60)
```
in this case it works as we have the infinit loop in the process

My confusion come from the different way for the thread to die in `init_scheduler` and `init_tasker`, at first it was suppose to react the same in my mind.

**Comment by riosw** [comment]
Regarding your confusion, perhaps it will be clearer after you better understand how processes and threads work.  But, 1 of the main idea that I am trying to convey is that — it is more important to not let the parent process die before the child. Parent is where you call `.start()`, child is the `target`. 

In the meantime, back to what you intend to do with the scheduler, I think you don't need to use multiprocess/threads at all. Not blocking your main program is exactly what `BackgroundScheduler` does. Have you tried this kind of structure from [this example](https://github.com/agronholm/apscheduler/blob/3.x/examples/schedulers/background.py)?

**Comment by dutangp** [comment]
hey, I forgot to thank you as I understand my confusion with my example and fixed my issue.

thanks for you patience and your explanation
