### ISSUE TITLE
self.engine.begin() as conn: AttributeError: __enter__

### ISSUE THREAD

**Issue by cburgess5294** [agronholm/apscheduler#743]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0.0a2

### What happened?

Running any of the WEB examples results in error:

[<user>@<server>apscheduler]$ uvicorn test3:app
INFO:     Started server process [874757]
INFO:     Waiting for application startup.
INFO:     ASGI 'lifespan' protocol appears unsupported.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
^CINFO:     Shutting down
INFO:     Finished server process [874757]
[<user>@<server> apscheduler]$ uvicorn test3:app --lifespan=on
INFO:     Started server process [875103]
INFO:     Waiting for application startup.
ERROR:    Exception in 'lifespan' protocol
Traceback (most recent call last):
  File "/home/burgesc/.local/lib/python3.9/site-packages/uvicorn/lifespan/on.py", line 88, in main
    await app(scope, self.receive, self.send)
  File "/home/burgesc/.local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/home/burgesc/.local/lib/python3.9/site-packages/fastapi/applications.py", line 282, in __call__
    await super().__call__(scope, receive, send)
  File "/home/burgesc/.local/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/burgesc/.local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/burgesc/apscheduler/test3.py", line 42, in __call__
    async with self.scheduler:
  File "/home/burgesc/.local/lib/python3.9/site-packages/apscheduler/schedulers/async_.py", line 82, in __aenter__
    await self._ensure_services_ready(self._exit_stack)
  File "/home/burgesc/.local/lib/python3.9/site-packages/apscheduler/schedulers/async_.py", line 111, in _ensure_services_ready
    await self.data_store.start(self.event_broker)
  File "/home/burgesc/.local/lib/python3.9/site-packages/apscheduler/datastores/async_adapter.py", line 36, in start
    await to_thread.run_sync(lambda: self.original.start(sync_event_broker))
  File "/home/burgesc/.local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/burgesc/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/burgesc/.local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/burgesc/.local/lib/python3.9/site-packages/apscheduler/datastores/async_adapter.py", line 36, in <lambda>
    await to_thread.run_sync(lambda: self.original.start(sync_event_broker))
  File "/home/burgesc/.local/lib/python3.9/site-packages/apscheduler/datastores/sqlalchemy.py", line 277, in start
    for attempt in self._retry():
  File "/home/burgesc/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 347, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/burgesc/.local/lib/python3.9/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result
[example1.txt](https://github.com/agronholm/apscheduler/files/11737021/example1.txt)
()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/burgesc/.local/lib/python3.9/site-packages/apscheduler/datastores/sqlalchemy.py", line 278, in start
    with attempt, self.engine.begin() as conn:
AttributeError: __enter__
ERROR:    Application startup failed. Exiting.

pip list:
Package           Version
----------------- -------
anyio             3.7.0
APScheduler       4.0.0a2
asyncpg           0.27.0
attrs             23.1.0
click             8.1.3
exceptiongroup    1.1.1
fastapi           0.97.0
greenlet          2.0.2
h11               0.14.0
idna              3.4
pip               20.2.4
pydantic          1.10.9
setuptools        50.3.2
sniffio           1.3.0
SQLAlchemy        2.0.0
starlette         0.27.0
tenacity          8.2.2
typing-extensions 4.6.3
tzlocal           5.0.1
uvicorn           0.22.0

Attemped with:
Python 3.9.16
Python 3.8.10

I have attempted to run the examples against both an internal and external postgres instance.

Code examples attached
[example2.txt](https://github.com/agronholm/apscheduler/files/11737024/example2.txt)
[example1.txt](https://github.com/agronholm/apscheduler/files/11737025/example1.txt)

### How can we reproduce the bug?

install recommended packages, run examples from WEB folder either directly or via uvicorn

**Comment by cburgess5294** [comment]
Turns out this issue is resolved if you make the following change to the examples:

   Import AsyncSQLAlchemyDataStore instead of SQLAlchemyDataStore:
      from apscheduler.datastores.async_sqlalchemy import AsyncSQLAlchemyDataStore
        instead of
      from apscheduler.datastores.sqlalchemy import SQLAlchemyDataStore
   
   Start data_store with  AsyncSQLAlchemyDataStore instead of SQLAlchemyDataStore:
      data_store = AsyncSQLAlchemyDataStore(engine)
        instead of
       data_store = SQLAlchemyDataStore(engine)

    Use SQLAlchemy library version 1.4.0 (using latest version 2.0.16 results in a different error)

**Comment by agronholm** [comment]
I think you might've been looking at examples from latest `master` instead of the `4.0.0a2` tag? The SQLAlchemy data stores have been unified since v4.0.0a2.
