### ISSUE TITLE
RuntimeError: cannot schedule new futures after interpreter shutdown when the job is triggered

### ISSUE THREAD

**Issue by Anzal-calixto** [agronholm/apscheduler#918]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

3.10.4

### What happened?

the expected behaviour is to run the scheduled job. 

But what happend was .
```
Error submitting job "job (trigger: cron[day_of_week='mon', hour='16', minute='4', second='0'], next run at: 2024-05-20 16:04:00 IST)" to executor "default"
Traceback (most recent call last):
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\schedulers\base.py", line 988, in _process_jobs
    executor.submit_job(job, run_times)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\executors\base.py", line 71, in submit_job
    self._do_submit_job(job, run_times)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python39\lib\site-packages\apscheduler\executors\pool.py", line 28, in _do_submit_job
    f = self._pool.submit(run_job, job, job._jobstore_alias, run_times, self._logger.name)
  File "C:\Users\rohit\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 163, in submit
    raise RuntimeError('cannot schedule new futures after '
RuntimeError: cannot schedule new futures after interpreter shutdown
```

### How can we reproduce the bug?

To reproduce the bug you can try this code which i was using 

```py
from threading import Thread
from apscheduler.schedulers.background import BackgroundScheduler
from apscheduler.jobstores.sqlalchemy import SQLAlchemyJobStore
from apscheduler.executors.pool import ThreadPoolExecutor
from apscheduler.triggers.cron import CronTrigger
from pytz import utc
from time import sleep



jobstores_1 = {'default': SQLAlchemyJobStore(
    url='sqlite:///jobs.db')}
executors_1 = {'default': ThreadPoolExecutor(20)}
job_defaults_1 = {'max_instances': 20}

scheduler_1 = BackgroundScheduler(
    jobstores=jobstores_1, executors=executors_1, job_defaults=job_defaults_1, timezone=utc)

scheduler_1.start()

def thread_1():
    while True:
        print("thread 1\n")
        sleep(5)

def thread_2():
    while True:
        print("thread 2\n")
        sleep(5)

def thread_3():
    while True:
        print("thread 3\n")
        sleep(5)

def thread_4():
    while True:
        print("thread 4\n")
        sleep(5)

def create_scheduled_job(job_func, day_of_week, hour, minute, second,scheduler, job_id):
    # Create a new BackgroundScheduler instance if jobstores, executors, or job_defaults are not provided
    


    # Create a cron trigger for each selected day of the week
    for day in day_of_week:
        scheduler.add_job(
            job_func,
            trigger=CronTrigger(day_of_week=day, hour=hour, minute=minute, second=second),
            id=f"{job_id}_{day}"  # Append the day to the job ID for uniqueness

        )

def job():
    for i in range(2):
        print(f"job{i}")

def main():

    thread_a = Thread(target= thread_1)
    thread_b = Thread(target= thread_2)
    thread_c = Thread(target= thread_3)
    thread_d = Thread(target= thread_4)



    thread_a.start()
    thread_b.start()
    thread_c.start()
    thread_d.start()
    create_scheduled_job(
        job,
        day_of_week= ["mon"], 
        hour=16,
        minute=10,
        second=0,
        scheduler=scheduler_1,
        job_id='job2',
    )


if __name__ == "__main__":
    main()
```

**Comment by agronholm** [comment]
So, how long do I need to run this script to reproduce the issue? From the looks of it, it only fires at 16:10 every Monday. Would an `IntervalTrigger` not reproduce it?

**Comment by agronholm** [comment]
Never mind, I was able to repro it after adjusting the time so it fires the job really soon.

**Comment by agronholm** [comment]
Looks like this can be reproed with just the default memory job store too.

**Comment by agronholm** [comment]
Ahhhh....I see the problem. The interpreter really DID shut down. I asked you about this and you denied it. But the script runs to completion and the only thing preventing it from shutting down are the non-daemonic threads you spawned. So to fix this, don't let the main thread run to completion. Use BlockingScheduler instead of BackgroundScheduler if you're not doing anything else in the main thread.

**Comment by agronholm** [comment]
Also relevant: https://apscheduler.readthedocs.io/en/3.x/faq.html#why-doesn-t-the-scheduler-run-my-jobs

**Comment by Anzal-calixto** [comment]
i didnt know if the interpreter was shutting down or not. sorry for not replying soon i live in india. i will try to run as you suggested
