### ISSUE TITLE
v4 Temporary data store error Scheduler crashed

### ISSUE THREAD

**Issue by ramki88** [agronholm/apscheduler#943]
### Things to check first

- [X] I have checked that my issue does not already have a solution in the [FAQ](https://apscheduler.readthedocs.io/en/master/faq.html)

- [X] I have searched the existing issues and didn't find my bug already reported there

- [X] I have checked that my bug is still present in the latest release

### Version

4.0.0a5

### What happened?

Scheduler keeps crashing. And requires a restart to resolve.
```
Temporary data store error (attempt 1): 
Scheduler crashed
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.12/site-packages/apscheduler/_schedulers/async_.py", line 784, in run_until_stopped
  |     async with create_task_group() as task_group:
  |   File "/usr/local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 2329, in connect
    |     return await connect_utils._connect(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 991, in _connect
    |     conn = await _connect_addr(
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    |     return await __connect_addr(params, True, *args)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    |     tr, pr = await connector
    |              ^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connect_utils.py", line 752, in _create_ssl_connection
    |     do_ssl_upgrade = await pr.on_data
    |                      ^^^^^^^^^^^^^^^^
    | asyncio.exceptions.CancelledError
    | 
    | The above exception was the direct cause of the following exception:
    | 
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.12/site-packages/apscheduler/_schedulers/async_.py", line 854, in _process_schedules
    |     schedules = await self.data_store.acquire_schedules(self.identity, 100)
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/apscheduler/datastores/sqlalchemy.py", line 592, in acquire_schedules
    |     async for attempt in self._retry():
    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 166, in __anext__
    |     do = await self.iter(retry_state=self._retry_state)
    |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/tenacity/asyncio/__init__.py", line 153, in iter
    |     result = await action(retry_state)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/tenacity/_utils.py", line 99, in inner
    |     return call(*args, **kwargs)
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 418, in exc_check
    |     raise retry_exc.reraise()
    |           ^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/tenacity/__init__.py", line 185, in reraise
    |     raise self.last_attempt.result()
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
    |     return self.__get_result()
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    |     raise self._exception
    |   File "/usr/local/lib/python3.12/site-packages/apscheduler/datastores/sqlalchemy.py", line 594, in acquire_schedules
    |     async with self._begin_transaction() as conn:
    |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    |     return await anext(self.gen)
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/apscheduler/datastores/sqlalchemy.py", line 201, in _begin_transaction
    |     conn = await async_cm.__aenter__()
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/contextlib.py", line 210, in __aenter__
    |     return await anext(self.gen)
    |            ^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 1063, in begin
    |     async with conn:
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/base.py", line 121, in __aenter__
    |     return await self.start(is_ctxmanager=True)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/ext/asyncio/engine.py", line 273, in start
    |     await greenlet_spawn(self.sync_engine.connect)
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 201, in greenlet_spawn
    |     result = context.throw(*sys.exc_info())
    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3276, in connect
    |     return self._connection_cls(self)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    |     self._dbapi_connection = engine.raw_connection()
    |                              ^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 3300, in raw_connection
    |     return self.pool.connect()
    |            ^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    |     return _ConnectionFairy._checkout(self)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    |     fairy = _ConnectionRecord.checkout(pool)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 717, in checkout
    |     with util.safe_reraise():
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    |     raise exc_value.with_traceback(exc_tb)
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 715, in checkout
    |     dbapi_connection = rec.get_connection()
    |                        ^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 866, in get_connection
    |     self.__connect()
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    |     with util.safe_reraise():
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    |     raise exc_value.with_traceback(exc_tb)
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    |     self.dbapi_connection = connection = pool._invoke_creator(self)
    |                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/create.py", line 643, in connect
    |     return dialect.connect(*cargs, **cparams)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 620, in connect
    |     return self.loaded_dbapi.connect(*cargs, **cparams)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 932, in connect
    |     await_only(creator_fn(*arg, **kw)),
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    |     return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    |     value = await result
    |             ^^^^^^^^^^^^
    |   File "/usr/local/lib/python3.12/site-packages/asyncpg/connection.py", line 2328, in connect
    |     async with compat.timeout(timeout):
    |   File "/usr/local/lib/python3.12/asyncio/timeouts.py", line 115, in __aexit__
    |     raise TimeoutError from exc_val
    | TimeoutError
    +------------------------------------
```

### How can we reproduce the bug?

```
from sqlalchemy.ext.asyncio import create_async_engine

async_engine = create_async_engine("postgresql+asyncpg://postgres:secret@localhost/testdb", connect_args{'server_settings': {'search_path': "test"}}, pool_size=10, max_overflow=2, pool_recycle=300, pool_pre_ping=True, pool_use_lifo=True)

data_store = SQLAlchemyDataStore(engine)
event_broker = AsyncpgEventBroker.from_async_sqla_engine(engine)
scheduler = AsyncScheduler(data_store, event_broker)
```

**Comment by agronholm** [comment]
If it can't connect to the database server, what would you have it do? Keep silently trying forever?

**Comment by ramki88** [comment]
Retry maybe? Can it retry for configurable number of times and then fail..

**Comment by agronholm** [comment]
It's a timeout error, so wouldn't that be the same as just increasing the timeout to a higher value?

**Comment by ramki88** [comment]
> It's a timeout error, so wouldn't that be the same as just increasing the timeout to a higher value?

Actually, it makes sense, my bad. Will have the connection timeout added in connect_args and check.. Thanks alot for all your efforts.
