### ISSUE TITLE
`print_job` delete jobs from jobstore if can't find func

### ISSUE THREAD

**Issue by agronholm** [agronholm/apscheduler#99]
Originally reported by: **Josh Purvis (Bitbucket: [joshpurvis](http://bitbucket.org/joshpurvis), GitHub: [joshpurvis](http://github.com/joshpurvis))**

---

This happened in some more complicated code, but I simplified and reproduced it from the command line like so:

I have this factory function which creates an instance of the scheduler with some given settings:

```
def get_apscheduler():

    jobstores = {'default': SQLAlchemyJobStore(engine=pg_engine)}
    executors = {'default': ThreadPoolExecutor(20)}
    job_defaults = {'coalesce': True, 'max_instances': 1}

    return BackgroundScheduler(
        jobstores=jobstores,
        executors=executors,
        job_defaults=job_defaults,
        timezone=pytz.utc,
    )
```

Now let's get an instance of the scheduler, add a job, then start it..

```
$ python
>>> scheduler = get_apscheduler():
>>> def foo(hey): print hey 
...
>>> scheduler.add_job(id='1', name='test job', func=foo,trigger='cron',args=['hey'], **{'second': '*/1'}) 
<Job (id=1 name=test job)>
>>> scheduler.start()
>>> hey
hey
hey
```

CTRL+C
Looks good so far..

Now in a new terminal, instance the scheduler again:

```
$ python
>>> scheduler = get_apscheduler()
>>> scheduler.print_jobs()
Jobstore default:
ERROR:apscheduler.jobstores:Unable to restore job "1" -- removing it
Traceback (most recent call last):
  File "/home/josh/.env/engine/local/lib/python2.7/site-packages/APScheduler-3.0.3-py2.7.egg/apscheduler/jobstores/sqlalchemy.py", line 126, in _get_jobs
    jobs.append(self._reconstitute_job(row.job_state))
  File "/home/josh/.env/engine/local/lib/python2.7/site-packages/APScheduler-3.0.3-py2.7.egg/apscheduler/jobstores/sqlalchemy.py", line 114, in _reconstitute_job
    job.__setstate__(job_state)
  File "/home/josh/.env/engine/local/lib/python2.7/site-packages/APScheduler-3.0.3-py2.7.egg/apscheduler/job.py", line 228, in __setstate__
    self.func = ref_to_obj(self.func_ref)
  File "/home/josh/.env/engine/local/lib/python2.7/site-packages/APScheduler-3.0.3-py2.7.egg/apscheduler/util.py", line 264, in ref_to_obj
    raise LookupError('Error resolving reference %s: error looking up object' % ref)
LookupError: Error resolving reference __main__:foo: error looking up object
    No scheduled jobs
```

Now since foo() is no longer in scope, it deletes the job from the SQLAlchemyJobStore without warning. Is this intended behavior? or am I doing something wrong? 

I'd like to think `print_jobs` would be a benign operation, regardless if a config mistake was made or not.. but in this case it wiped out my entire `apscheduler_jobs` table:

```
select * from apscheduler_jobs ;
 id | next_run_time | job_state 
----+---------------+-----------
(0 rows)
```

---
- Bitbucket: https://bitbucket.org/agronholm/apscheduler/issue/99

**Comment by agronholm** [comment]
The failure to locate a task function no longer causes anything to be automatically deleted in v4.0.0a1, so I'm closing this.
